### ISSUE TITLE
Deepspeech2 training error

### ISSUE THREAD

**Issue by hasangchun** [sooftware/OpenSpeech#23]
## Environment info
- Platform: Windows 10
- Python version: 3.7
- PyTorch version (GPU?): PyTorch version : 1.8.1, CUDA version : 10.2
- Using GPU in script?: GeForce RTX 2080 Ti
  
## Information

Model I am using (ListenAttendSpell, Transformer, Conformer ...):  Deepspeech2, listen_attend_spell_with_multi_head

command : 
```
$ python ./openspeech_cli/hydra_train.py \
    dataset=ksponspeech \
    dataset.dataset_path=E:/KsponSpeech \
    dataset.manifest_file_path=E:/kspon_character_manifest.txt \  
    dataset.test_dataset_path=E:/test \
    dataset.test_manifest_dir=E:/KsponSpeech_scripts \
    vocab=kspon_character \
    model=deepspeech2\
    audio=melspectrogram \
    lr_scheduler=warmup_reduce_lr_on_plateau \
    trainer=gpu \
    criterion=ctc
```
The problem arises when using:

```
  | Name      | Type        | Params
------------------------------------------
0 | criterion | CTCLoss     | 0     
1 | encoder   | DeepSpeech2 | 90.2 M
------------------------------------------
90.2 M    Trainable params
0         Non-trainable params
90.2 M    Total params
360.606   Total estimated model params size (MB)
Global seed set to 1
Epoch 0:   1%|▏         | 4254/310637 [1:02:37<75:09:50,  1.13it/s, loss=9.13, v_num=0]Traceback (most recent call last):
  File "C:/Users/cote/PycharmProjects/kospeech2/openspeech_cli/hydra_train.py", line 51, in hydra_main
    trainer.fit(model, data_module)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 458, in fit
    self._run(model)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 756, in _run
    self.dispatch()
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 797, in dispatch
    self.accelerator.start_training(self)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 96, in start_training
    self.training_type_plugin.start_training(trainer)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 144, in start_training
    self._results = trainer.run_stage()
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 807, in run_stage
    return self.run_train()
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\trainer.py", line 869, in run_train
    self.train_loop.run_training_epoch()
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 490, in run_training_epoch
    batch_output = self.run_training_batch(batch, batch_idx, dataloader_idx)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 731, in run_training_batch
    self.optimizer_step(optimizer, opt_idx, batch_idx, train_step_and_backward_closure)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 432, in optimizer_step
    using_lbfgs=is_lbfgs,
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\core\lightning.py", line 1403, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\core\optimizer.py", line 214, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\core\optimizer.py", line 134, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 329, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 336, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\plugins\training_type\training_type_plugin.py", line 193, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\torch\optim\optimizer.py", line 89, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\torch\autograd\grad_mode.py", line 27, in decorate_context
    return func(*args, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\torch\optim\adam.py", line 66, in step
    loss = closure()
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 726, in train_step_and_backward_closure
    split_batch, batch_idx, opt_idx, optimizer, self.trainer.hiddens
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 827, in training_step_and_backward
    self.backward(result, optimizer, opt_idx)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\trainer\training_loop.py", line 865, in backward
    result.closure_loss, optimizer, opt_idx, should_accumulate, *args, **kwargs
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\accelerators\accelerator.py", line 309, in backward
    self.lightning_module, closure_loss, optimizer, optimizer_idx, should_accumulate, *args, **kwargs
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\plugins\precision\precision_plugin.py", line 79, in backward
    model.backward(closure_loss, optimizer, opt_idx)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\pytorch_lightning\core\lightning.py", line 1275, in backward
    loss.backward(*args, **kwargs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\torch\tensor.py", line 245, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph, inputs=inputs)
  File "C:\Users\cote\Anaconda3\envs\sc\lib\site-packages\torch\autograd\__init__.py", line 147, in backward
    allow_unreachable=True, accumulate_grad=True)  # allow_unreachable flag

RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```

The above error occurred while training Deepspeech2, and the same error occurred in the listen_attend_spell_with_multi_head model.

**Comment by hasangchun** [comment]
https://github.com/NVIDIA/tacotron2/issues/109

**Comment by sooftware** [comment]
Can you check if the Cuda version matches the Pytorch installation command?

**Comment by sooftware** [comment]
It maybe your environment error.

**Comment by jun-danieloh** [comment]
What was your exact workaround here? I am facing same issues. In the post(NVIDIA/tacotron2#109) pasted above, it recommends to just uninstall and reinstall PyTorch or so. Some people mentions that just reducing the batch size works for this issue. Can you share what was your exact WA?

My logs are below:
```
Epoch 0:   4%| | 1450/35504 [09:05<3:33:34,  2.66it/s, loss=nan, v_num=abtb, train_loss=nan.0, train_wer=0.901, train_Error executing job with overrides: ['dataset.dataset_path=/home/jun1.oh/', 'dataset.dataset_download=False', 'dataset.
manifest_file_path=/home/jun1.oh/LibriSpeech_daniel/libri_subword_manifest.txt', 'tokenizer.vocab_path=/home/jun1.oh/LibriSpeech_daniel/', 'trainer.batch_size=16']
Traceback (most recent call last):
  File "./openspeech_cli/hydra_train.py", line 60, in <module>
    hydra_main()
  File "/opt/conda/lib/python3.8/site-packages/hydra/main.py", line 48, in decorated_main
    _run_hydra(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 377, in _run_hydra
    run_and_report(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 214, in run_and_report
    raise ex
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 211, in run_and_report
    return func()
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/utils.py", line 378, in <lambda>
    lambda: hydra.run(
  File "/opt/conda/lib/python3.8/site-packages/hydra/_internal/hydra.py", line 111, in run
    _ = ret.return_value
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 233, in return_value
    raise self._return_value
  File "/opt/conda/lib/python3.8/site-packages/hydra/core/utils.py", line 160, in run_job
    ret.return_value = task_function(task_cfg)
  File "./openspeech_cli/hydra_train.py", line 54, in hydra_main
    trainer.fit(model, data_module)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 552, in fit
    self._run(model)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 917, in _run
    self._dispatch()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 985, in _dispatch
    self.accelerator.start_training(self)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 92, in start_training
    self.training_type_plugin.start_training(trainer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 161, in start_training
    self._results = trainer.run_stage()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 995, in run_stage
    return self._run_train()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/trainer/trainer.py", line 1044, in _run_train
    self.fit_loop.run()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/fit_loop.py", line 200, in advance
    epoch_output = self.epoch_loop.run(train_dataloader)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/epoch/training_epoch_loop.py", line 130, in advance
    batch_output = self.batch_loop.run(batch, self.iteration_count, self._dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 100, in run
    super().run(batch, batch_idx, dataloader_idx)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/base.py", line 111, in run
    self.advance(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 147, in advance
    result = self._run_optimization(batch_idx, split_batch, opt_idx, optimizer)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 201, in _run_optimization                                                                                               [40/83859]
    self._optimizer_step(optimizer, opt_idx, batch_idx, closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 395, in _optimizer_step
    model_ref.optimizer_step(
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/lightning.py", line 1618, in optimizer_step
    optimizer.step(closure=optimizer_closure)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 209, in step
    self.__optimizer_step(*args, closure=closure, profiler_name=profiler_name, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/core/optimizer.py", line 129, in __optimizer_step
    trainer.accelerator.optimizer_step(optimizer, self._optimizer_idx, lambda_closure=closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 296, in optimizer_step
    self.run_optimizer_step(optimizer, opt_idx, lambda_closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 303, in run_optimizer_step
    self.training_type_plugin.optimizer_step(optimizer, lambda_closure=lambda_closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/training_type_plugin.py", line 226, in optimizer_step
    optimizer.step(closure=lambda_closure, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/autograd/grad_mode.py", line 26, in decorate_context
    return func(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/optim/adam.py", line 66, in step
    loss = closure()
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 235, in _training_step_and_backward_closure
    result = self.training_step_and_backward(split_batch, batch_idx, opt_idx, optimizer, hiddens)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 536, in training_step_and_backward
    result = self._training_step(split_batch, batch_idx, opt_idx, hiddens)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/loops/batch/training_batch_loop.py", line 306, in _training_step
    training_step_output = self.trainer.accelerator.training_step(step_kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/accelerators/accelerator.py", line 193, in training_step
    return self.training_type_plugin.training_step(*step_kwargs.values())
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/plugins/training_type/dp.py", line 93, in training_step
    return self.model(*args, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/parallel/data_parallel.py", line 159, in forward
    return self.module(*inputs[0], **kwargs[0])
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/overrides/data_parallel.py", line 63, in forward
    output = super().forward(*inputs, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/pytorch_lightning/overrides/base.py", line 82, in forward
    output = self.module.training_step(*inputs, **kwargs)
  File "/home/jun1.oh/workspace/openspeech/openspeech/models/openspeech_encoder_decoder_model.py", line 166, in training_step
    logits = self.decoder(
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/jun1.oh/workspace/openspeech/openspeech/decoders/lstm_attention_decoder.py", line 192, in forward
    step_outputs, hidden_states, attn = self.forward_step(
  File "/home/jun1.oh/workspace/openspeech/openspeech/decoders/lstm_attention_decoder.py", line 146, in forward_step
    outputs, hidden_states = self.rnn(embedded, hidden_states)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/opt/conda/lib/python3.8/site-packages/torch/nn/modules/rnn.py", line 581, in forward
    result = _VF.lstm(input, hx, self._flat_weights, self.bias, self.num_layers,
RuntimeError: cuDNN error: CUDNN_STATUS_EXECUTION_FAILED
```
